version: '3.8'

services:
  beets-frontend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /home/agosha/.config/beets:/config
      - /home/agosha/.config/beets:/library
      - /DATA/Media/Music:/music
    environment:
      - BEETSDIR=/config
      - FLASK_ENV=production
      - FLASK_DEBUG=0
    restart: unless-stopped
    user: "1000:1000"
